spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/afina_db
    username: afina_app
    password: aAnatolikanibal12!
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      keepalive-time: 300000
      connection-test-query: "SELECT 1"
      pool-name: AfinaHikariPool
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/afina_db
    user: afina_migrator
    password: aAnatolikanibal12!
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    table: flyway_schema_history

app:
  mail:
    mode: log
